name: 'Set up Node'
description: 'Installs node and dependencies'

# branding:
#   icon: 'bookmark'
#   color: 'purple'

inputs:
  node-version:
    description: 'Node version'
    default: 20
    required: true

# outputs:
#   semver:
#     description: 'The next semantic version.'

runs:
  using: "composite"
  steps:

    - name: Set up node 20
      uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: npm ci
