name: ci-workflow
run-name: ${{ github.actor }} ci-workflow
on: [push, workflow_dispatch]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
      - name: Download Node modules
        run: npm ci
      - name: Lint, Typecheck
        run: |
          npm run prettier
          npm run typecheck
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: upload-pages-artifact@v3
        with:
          path: 'dist/'
  cd-pipeline:
    runs-on: ubuntu-latest
    needs: [ci-pipeline]
    environment: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Publish
        uses: actions/deploy-pages@v4
        

      
