name: ci-workflow
run-name: ${{ github.actor }} ci-workflow
on: [push, workflow_dispatch]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/actions/install
        with:
          node-version: 20
      - name: Lint, Typecheck
        run: |
          npm run prettier
          npm run typecheck
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'
  cd-pipeline:
    runs-on: ubuntu-latest
    needs: [ci-pipeline]
    environment: 
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Publish
        id: publish
        uses: actions/deploy-pages@v4
    outputs:
      url: ${{ steps.publish.outputs.page_url }}
  smoke-test:
    needs: cd-pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        browser: ["chromium", "firefox"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up
        uses: actions/install@v1
        with:
          node-version: 20
      - name: Install Playwright Browsers
        run: npx playwright install ${{ matrix.browser }}

      - name: Run Playwright tests
        run: npx playwright test --project ${{ matrix.browser }}
        env:
          PLAYWRIGHT_BASE_URL: ${{ needs.cd-pipeline.outputs.url }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 1

      
